version: 3
services:
  redis:
    image: redis
    networks:
      - back-end
  db:
    image: postgres
    networks:
      - back-end
  vote:
    build: ./vote
    ports:
      - 5000:80
    networks:
      - front-end
      - backend-end
  result:
    build: ./result
    ports:
      - 5001:80
    networks:
      - front-end
      - backend-end
  worker:
    build: ./worker

networks:
  front-end:
  back-end: